### ISSUE TITLE
iOS 1.1.0 app crashes on msp connect

### ISSUE THREAD

**Issue by jackooooo** [zosko/iNavTelemetry#3]
@jackooooo download new version from AppStore 1.1.0 that support MSP, i did not tested on iPhone because i dont have currently setup, i have only tested via USB on MacOS version of iNav Telemetry. Open new thread on issues to continue discussion about version is it working good MSPv2 on iOS devices.

_Originally posted by @zosko in https://github.com/zosko/iNavTelemetry/issues/2#issuecomment-890568312_

**Comment by jackooooo** [comment]
Zosko 
Tried the new updated iOS app. I can choose msp and click connect but the app crashes 80% of the time. Sometimes it gets the telemetry and updates when you move the FC. Happy to beta test if you like. Might get more crash logs then.

**Comment by zosko** [comment]
Let me bump new version and i will invite for Beta test, we should quick fix that issue.

**Comment by jackooooo** [comment]
Sounds like a plan. I'm also hoping to use a s.port version for my long range Fpv plane. I've got all the hardware now for the signal inverter
    On Tuesday, 17 August 2021, 07:06:40 am AEST, Bosko ***@***.***> wrote:  
 
 


Let me bump new version and i will invite for Beta test, we should quick fix that issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zosko** [comment]
@jackooooo  please try to download beta version from this link:

https://testflight.apple.com/join/7jfCnnmV

Use TestFlight Application to download it.

Let me know if this version crash.

**Comment by jackooooo** [comment]
Been using the Beta, and sent in a few crash logs to you. Hope it helps

**Comment by zosko** [comment]
i released new build 2, please download from TestFlight and try it

**Comment by jackooooo** [comment]
Still crashing, maybe not as much. 
Btw I made a signal inverter but it doesn’t seem to be working, not receiving anything over s.port into inav telemetry.  The voltage is ok (3v) light is flashing on the Bluetooth module, but no idea how to check if it’s sending data. Yaapu script is working fine so I know the telemetry is coming over smartport. I followed this YouTube video https://m.youtube.com/watch?v=lmSMt6JLWL8. Baud rate is 38400

**Comment by zosko** [comment]
for MSP on USB i did not notice any crash, but however i need to make test with Bluetooth, or even better to purchase FC like your that have built in bluetooth. Its hard to find where is crashing because on crash logs i dont see too much. 

What equipment you have ?

S.Port i tested on R9M ACCESS / ACCST. When i was on ACCST with my Taranis i was need to make Signal Inverter so from R9M i S.Port pin on backside to send telemetry via bluetooth to my application or tracker.  When i change to ACCESS, pins on R9M did not work anymore, so i was need to add Bluetooth to my taranis inside in case and it was work without inverting in that case. Btw. i have R9M 2019 and Taranis X9D 2019

Btw....  S.Port Baud rate is 57600, it will not work on 38400

**Comment by zosko** [comment]
>  Baud rate is 38400
S.Port Baud rate is 57600, it will not work on 38400

**Comment by zosko** [comment]
@jackooooo i added new version Build 3, please test that one. What i want to know is next:

1. is it crashing 
2. did values are correct presented on application

For values, i think only "Armed" and "FlyMode" are n/a because i dont know from where to get it, but i will figure out.

For crashing meantime if i not fix it like now "remote way" i will wait to receive flight controller like your so i can fix all crash.

**Comment by jackooooo** [comment]
I have a matek 405SE Wing flight controller. Taranis x9d radio with r9m. I think it’s the old protocol ACCST version.
I’ve set the baud rate to 57600 but need to resolder up the inverter again to test it out. 
Apparently you need the set the Serial setting to mirror telemetry in the Hardware menu on the x9d so it sends the telemetry to the R9M module smartport. Haven’t tested that myself yet.

**Comment by zosko** [comment]
If you have ability to mirror seems tou have older taranis that not support ACCESS. Yes you need to resolder because to program bluetooth you need to do without inverter. But you not need to connect to your back port on battery side, i think that is not inverted, inverted is only on back of R9M three pins (S.Port, Gnd, Vcc). Bu that is for Smart Port, i was think to test MSP protocol.

**Comment by jackooooo** [comment]
Okay. I also have a HM11 Bluetooth module connected up directly to the 405se FC with msp output so I can use it to configure inav on the ground with speedybee and check status with your app.I’m wanting to use the smartport and the HCO5 on my X9D for in flight status and seeing it on the map on my iPhone.

**Comment by jackooooo** [comment]
Got my signal inverter working after changing baud to 57600. Serial Port off in Hardware X9D menu. Testing smart port and it connects ok. Not updating artificial horizon tho. Only seems to show manual and angle mode options too. Everything else is updating ok. 
Had a problem after multiple connection/disconnections, it would not show the bt module anymore. And the bt module light was not flashing. It’s like the bt module was still paired after you hit disconnect? I noticed too after few connects the online counter would be 2 or 3. Had to turn off Bluetooth on my phone to get it to show the bt module again. 
MSP option still crashes on connect. 
My R9M module is ACCST and Taranis X9D is a 2015 version with opentx 2.3.11. HC05 BT module for s.port. This one https://www.ebay.com.au/itm/HC-05-Wireless-Bluetooth-Module-Master-Slave-for-Arduino-Fast-Shipping-/164970766406

**Comment by zosko** [comment]
To show horisontal and vertical you need in CLI in iNav to write

smartport_fuel_unit = PERCENT
frsky_pitch_roll = ON

Problem with disconnect/connect maybe because you are too close or too far from bluetooth, i will make fix for that to autoconnect when is lose connection.

Counter for online users is just indicator for current online users.

For MSP issue i will fix that next week and i will let you know next time for all bug fixes. I will make test on real flights for MSP and S.Port to be sure all is working.

**Comment by jackooooo** [comment]
Thanks, working now. I did have to delete all sensors in the Telemetry menu and then Discover new sensors to get the pitch and roll sensors to show up in the inav Lua script again after I turned frsky_pitch_roll = ON. Before I did that the pitch and roll no longer updated in the Lua Script, but did in the app. 
Are you going to animate the attitude indicator (artificial horizon) in the future, or just have it static with white line for pitch and orange line for roll?
Like this:
http://learntoflyblog.com/wp-content/uploads/2016/03/7-24.png

**Comment by zosko** [comment]
@jackooooo in next days i will make complete test on S.Port and MSP to verify where is crashing and fix bugs, i prepare quad for that.

**Comment by jackooooo** [comment]
Cool. I loaded the code into Xcode and ran it on my iPhone X. Got the following error:
Thread 1: Fatal error: Index out of range. Line 120 of MSP.swift
This bit of code?
 private func buffer_get_int16(buffer: [UInt8], index : Int) -> Int16{
        return Int16(buffer[index]) << 8 | Int16(buffer[index - 1])

In the buffer:
buffer	[UInt8]	11 values	
[0]	UInt8	2
[1]	UInt8	5
[2]	UInt8	241
[3]	UInt8	103
[4]	UInt8	172
[5]	UInt8	234
[6]	UInt8	239
[7]	UInt8	108
[8]	UInt8	231
[9]	UInt8	88
[10]	UInt8	52
index	Int	11
self	iNavTelemetry.MSP	0x0000000283b90d00
ObjectiveC.NSObject	NSObject	
packet	iNavTelemetry.TelemetryStruct	

I've only ever used Xcode to side load apps so not sure how to get proper logs out
<img width="715" alt="Screen Shot 2021-08-28 at 11 33 04 pm" src="https://user-images.githubusercontent.com/37430938/131241152-02b08e15-2eb0-4d9a-8e65-452d0f13d435.png">

**Comment by zosko** [comment]
@jackooooo Yea yesterday i have add bluetooth to my FC and tested MSP, i fixed all bugs, not crash anymore. I will prepare version beta for testing.

**Comment by jackooooo** [comment]
Congrats!

**Comment by zosko** [comment]
Hey @jackooooo last version "1.1.1 (5)" should work everything about MSP except "Fuel" , because that is not included in telemetry, that works only on SmartPort. If you want you can test that version, im planing to put on AppStore soon

**Comment by jackooooo** [comment]
Yup. Working for me now. Nice. 
Only thing outstanding is it’s only showing manual and acro modes. I’ve got RTL, cruise, launch, loiter modes setup and it only shows acro mode when I switch to those modes

**Comment by zosko** [comment]
@jackooooo cool
yea for now i support only Manual, Angle and Horizon. In next versions i can make improvements on that. Also i want to change little layout of application to look nicer. I will close now issue because is solved. Thank you for helping me ;)
